name: automatic builds
run-name: ${{ github.actor }} building flutter
on: [push]
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build web
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-dist
        path: build/web/
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build apk --split-per-abi
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apk-dist
        path: build/app/outputs/flutter-apk/*.apk
