name: automatic builds
run-name: ${{ github.actor }} building flutter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build web
    - run: flutter build apk --split-per-abi
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: upload-apk
        path: |
          *.apk
