name: Autobuild
run-name: ${{ github.actor }} building flutter
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:version:-:hash:'
          cache-path: ${{ runner.tool_cache }}/flutter/ # optional, change this to specify the cache path
      - name: Install Dependencies
        run: flutter pub get
  build-web:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - name: Build
      run: flutter build web
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-dist
        path: build/web/
  build-apk:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - name: Build
      run: flutter build apk --split-per-abi
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk-dist
        path: build/app/outputs/flutter-apk/*.apk