name: Autobuild
run-name: ${{ github.actor }} building flutter
on: [push]
jobs:
  cache:
    steps:
      uses: actions/cache@v3.2.6
      with:
        path: ".dart_tool"
        enableCrossOsArchive: true
  build-web:
    needs: cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build web
  build-apk:
    needs: cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build apk --split-per-abi
  upload:
    runs-on: ubuntu-latest
    needs: [build-web, build-apk]
    steps:
      - name: Upload Built Web Server
        uses: actions/upload-artifact@v3
        with:
          name: web-dist
          path: build/web/
      - name: Upload Built APKs
        uses: actions/upload-artifact@v3
        with:
          name: apk-dist
          path: build/app/outputs/flutter-apk/*.apk
