name: Autobuild
run-name: ${{ github.actor }} building flutter
on: [push]
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3.2.6
        with:
          path: ${{ env.PUB_CACHE }}
          key: deps-${{ hashFiles('**/pubspec.lock') }}
      - name: Cache Flutter SDK
        uses: actions/cache@v3.2.6
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
  build-web:
    needs: cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build web
  build-apk:
    needs: cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter build apk --split-per-abi
  upload:
    runs-on: ubuntu-latest
    needs: [build-web, build-apk]
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: web-dist
          path: build/web/
      - uses: actions/upload-artifact@v3
        with:
          name: apk-dist
          path: build/app/outputs/flutter-apk/*.apk
